version: "3.1"
assistant_id: "shell-customer-service-assistant"
language: "en"

policies:
  - name: FlowPolicy
  - name: EnterpriseSearchPolicy
    vector_store:
      type: faiss
      source: ./docs
      threshold: 0.0
      chunk_size: 500
      chunk_overlap: 100
      max_chunks: 1000
    llm:
      model_group: enterprise_search_generation
    embeddings:
      model_group: enterprise_search_embeddings
    fallback_action: null

pipeline:
  - name: SearchReadyLLMCommandGenerator
    llm:
      model_group: command_generator_llm
